//questions for game
var question1="How would you describe yourself?"
var question2="In what positon do you sleep? "
var question3="How do you manage your money?"
var question4="What's your greatest fear?"
var question5="In a relationship which do you find more important?"
var question6="While working with others you are the...?"
var question7="What's one bad trait do you have?"
var question8="Pick a color."
var question9="Someone really messes up, how forgiving are you?"
var question10=""
var question11=""
var question12=""
var question13=""
var question14=""
var question15=""

//answers to questions
var answer1A="Responsible"
var answer1B="Indepentable"
var answer1C="Caring"
var answer1D="None/I'm not sure"

var answer2A="Stomach"
var answer2B="On your back"
var answer2C="Toss and turn"
var answer2D="Other"

var answer3A="Hates to spend a penny"
var answer3B="Save half and spends half"
var answer3C="It's hard to keep a penny"
var answer3D="None/ I'm not sure"

var answer4A="Wild Animals"
var answer4B="Heights"
var answer4C="Being Alone"
var answer4D="Me? Scared? Please."

var answer5A="Loyalty"
var answer5B="Communication"
var answer5C="Cuddling"
var answer5D="Your partners Income"

var answer6A="Bossy one"
var answer6B="One who can be more serious"
var answer6C="Quiet"
var answer6D="None/ I'm not sure"

var answer7A="Stubborn"
var answer7B="Moody"
var answer7C="Lazy"
var answer7D="others"

var answer8A="Black"
var answer8B="Blue"
var answer8C="Red"
var answer8D="Yellow"

var answer9A="Unforgiving"
var answer9B="Takes time but give it a while"
var answer9C="Always give second chances"
var answer9D="Depends the situation"

var answer10A=""
var answer10B=""
var answer10C=""
var answer10D=""

var answer11A=""
var answer11B=""
var answer11C=""
var answer11D=""

var answer12A=""
var answer12B=""
var answer12C=""
var answer12D=""

var answer13A=""
var answer13B=""
var answer13C=""
var answer13D=""

var answer14A=""
var answer14B=""
var answer14C=""
var answer14D=""

var answer15A=""
var answer15B=""
var answer15C=""
var answer15D=""
